### ISSUE TITLE
Platform: Comment button does not appear on text with a superscript

### ISSUE THREAD

**Issue by Sebastian-ubs** [BiblioNexus-Foundation/scripture-editors#128]
Double clicking a word with a superscript does not bring up the comment button
![grafik](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/ca22ddeb-c7de-4437-a72d-dd299f328ec0)

**Comment by irahopkinson** [comment]
@Sebastian-ubs thanks for finding that. Yes you can't comment on a footnote/xref which is currently included in your selection. A work-around for now is to manually select the word (rather than use double-click). I'll need to figure out how to fix the double-click selection to not include the footnote/xref.
